wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    code_path: code/examples/RNN_Example.py
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.4
    t:
      4: 3.9.4
      5: 0.10.27
      8:
      - 3
      - 5
