name: Deploy to Firebase Hosting
'on':
  push:
    branches: [ main, 0.0.19 ]
  pull_request:
    branches: [ main, 0.0.19 ]
env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create build
        working-directory: ./docs
        run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AIINPY }}'
          channelId: live
          projectId: aiinpy
          entryPoint: ./docs
