
name: test models
on: [push]
jobs:

  cnn-mnist:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: cd example && python3 cnn-mnist.py

    
  cnn-cifar10:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: cd example && python3 cnn-cifar10.py

    
  lstm-timeseries:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: cd example && python3 lstm-timeseries.py

    
  gru-timeseries:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: cd example && python3 gru-timeseries.py

    
  rnn-timeseries:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: cd example && python3 rnn-timeseries.py

    
  rnn-posnegcon:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: cd example && python3 rnn-posnegcon.py

    
  nn-andor:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: cd example && python3 nn-andor.py

    
  nn-nonlinearity:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: cd example && python3 nn-nonlinearity.py

    